quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: 121314Ma
    jdbc: false
    reactive:
      url: postgresql://localhost:5432/quarkus_test
  hibernate-orm:
    database:
      generation: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
#  log:
#    level: DEBUG
kafka:
  bootstrap:
    servers: localhost:9092
mp:
  messaging:
    incoming:
      test:
        topic: test
        connector: smallrye-kafka
        failure-strategy: ignore